### PR TITLE
Add generate command

### PR DESCRIPTION
**Pull request by borismod**
## Description
Generate command generates data_model.py file based on shell-definition.yml and its imports.

## Related Stories
connect #76

## Breaking
NO

---
This change is [Reviewable](https://reviewable.io/reviews/qualisystems/shellfoundry/77)

### CODE REVIEW

**Comment by doppleware** [comment]
Reviewed 13 of 15 files at r1.
Review status: 13 of 15 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[shellfoundry/utilities/temp_dir_context.py, line 16 at r1](https://reviewable.io:443/reviews/qualisystems/shellfoundry/77#-KS0IAdX51BSKizqtMoH:-KS0IAdX51BSKizqtMoI:bv3effl) ([raw file](https://github.com/qualisystems/shellfoundry/blob/61b9d0fd853a6f3239502bc17245e5a003e7e59f/shellfoundry/utilities/temp_dir_context.py#L16)):*
> ```Python
> 
>     def __exit__(self, exc_type, exc_val, exc_tb):
>         if exc_val:
> ```

Add a parameter in constructor 'remove files on error' default = true, change to false in tests

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/shellfoundry/77)*

**Comment by doppleware** [comment]
Reviewed 2 of 15 files at r1.
Review status: 14 of 15 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/shellfoundry/77)*

**Comment by doppleware** [comment]
Reviewed 1 of 15 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/shellfoundry/77)*

**Comment by borismod** [comment]
Review status: 13 of 16 files reviewed at latest revision, 1 unresolved discussion.

---

*[shellfoundry/utilities/temp_dir_context.py, line 16 at r1](https://reviewable.io:443/reviews/qualisystems/shellfoundry/77#-KS0IAdX51BSKizqtMoH:-KS1DrvlribeTHYxaPY8:b-896fix) ([raw file](https://github.com/qualisystems/shellfoundry/blob/61b9d0fd853a6f3239502bc17245e5a003e7e59f/shellfoundry/utilities/temp_dir_context.py#L16)):*
<details><summary><i>Previously, doppleware (Roni Dover) wrote…</i></summary>
> Add a parameter in constructor 'remove files on error' default = true, change to false in tests
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/shellfoundry/77)*

**Comment by borismod** [comment]
Reviewed 1 of 15 files at r1.
Review status: 13 of 16 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[shellfoundry/utilities/temp_dir_context.py, line 16 at r1](https://reviewable.io:443/reviews/qualisystems/shellfoundry/77#-KS0IAdX51BSKizqtMoH:-KS1E2i1XVtl0H5CeZYQ:b-896fix) ([raw file](https://github.com/qualisystems/shellfoundry/blob/61b9d0fd853a6f3239502bc17245e5a003e7e59f/shellfoundry/utilities/temp_dir_context.py#L16)):*
<details><summary><i>Previously, borismod (Boris Modylevsky) wrote…</i></summary>
> Done.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/shellfoundry/77)*

**Comment by borismod** [comment]
Reviewed 1 of 2 files at r3.
Review status: 14 of 16 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/shellfoundry/77)*

**Comment by borismod** [comment]
Reviewed 13 of 15 files at r1, 1 of 1 files at r2, 1 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/shellfoundry/77)*

**Comment by borismod** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/shellfoundry/77)*

**Comment by borismod** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/shellfoundry/77)*

**Pull request merged**
