### PR TITLE
Alco readme

### PR DESCRIPTION
**Pull request by ricardoalcocer**
## Description

Made the README more useful, organized and readable.  Please consider merging.
## Related Stories

none
## Breaking

NO
## Breaking changes
- none

---

This change is [Reviewable](https://reviewable.io/reviews/qualisystems/shellfoundry/90)

### CODE REVIEW

**Comment by borismod** [comment]
@ricardoalcocer thanks for contributing to ShellFoundry. It seems that the branch is out of date, can you please update it? 
BTW, we're in transition from Markdown to ReStructured Text format for Python packages. RST format is preferable as it can be embedded into Python package and appears on Pypy.

**Comment by ricardoalcocer** [comment]
Hey @borismod , so my only change is in the README.md file.  Did you want me to try to push that file to master?

**Comment by borismod** [comment]
@ricardoalcocer thanks for your contribution, it really looks much better! I have only small comment regarding this sentence: 

> ShellFoundry performs the same tasks as our PyCharm plugin

Although there is an overlap between the two, but there is still a difference. ShellFoundry creates and installs a shell, which is contained of data model and a driver. While PyCharm plugin only allows to publish the driver (even not create a new one), which is a subset of a shell. So using only the plugin, the user will be required to define the data model using RM client or import a package with the data model and to create the driver manually. There are some plans to add to the plugin the same functionalities that exist in ShellFoundry.

**Could you please modify that sentence?**

**Comment by borismod** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/shellfoundry/90)*

**Pull request merged**
