### PR TITLE
support driver versions to dynamically change

### PR DESCRIPTION
**Pull request by kalsky**
When setting the drivermetadata.xml with a version like '1.0.*', the version will get replaced just before installation with a dynamic version such as 1.0.6071.20302.
where the build number (6071) is the number of days since 1/1/2000, and the revision number is the number of seconds since midnight/2.

then the xml file will get the original 1.0.* after the packaging is done.

---
This change is [Reviewable](https://reviewable.io/reviews/qualisystems/shellfoundry/65)

### CODE REVIEW

**Comment by kalsky** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[shellfoundry/utilities/package_builder.py, line 112 \[r1\]](https://reviewable.io:443/reviews/qualisystems/shellfoundry/65#-KQN62qzuROhIzu2LUSS:-KQWSKzqtDfECkv8-v5i:bb7f2mf) ([raw file](https://github.com/qualisystems/shellfoundry/blob/532684db7b7569fd0c78d3cbb895b5012c0b875a/shellfoundry/utilities/package_builder.py#L112)):*
<details><summary><i>Previously, doppleware (Roni Dover) wrote…</i></summary>
> Wouldn't it be better to use the XSD instead of regex search on the string?
</details>
done

---

*[shellfoundry/utilities/package_builder.py, line 118 \[r1\]](https://reviewable.io:443/reviews/qualisystems/shellfoundry/65#-KQN6CdZf0d75nzr_ENT:-KQWSLt8Gu6uvWVxkw5w:bb7f2mf) ([raw file](https://github.com/qualisystems/shellfoundry/blob/532684db7b7569fd0c78d3cbb895b5012c0b875a/shellfoundry/utilities/package_builder.py#L118)):*
<details><summary><i>Previously, doppleware (Roni Dover) wrote…</i></summary>
> I would extract the version strategy into its own class, This makes it easier to update/replace and test (if you want to run tests that check for a specific version)
</details>
done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/shellfoundry/65)*

**Comment by doppleware** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/test_utilities/test_package_builder.py, line 146 \[r2\]](https://reviewable.io:443/reviews/qualisystems/shellfoundry/65#-KQWvlHDfDbNL6hXGpuB:-KQWvlHDfDbNL6hXGpuC:by2p1c0) ([raw file](https://github.com/qualisystems/shellfoundry/blob/2c1a17b362bded70465a2e2295b3a70a9e567b5c/tests/test_utilities/test_package_builder.py#L146)):*
> ```Python
>         assertFileExists(self, 'aws/amazon_web_services/package/Resource Drivers - Python/AwsDriver.zip')
> 
>     def test_it_updates_the_driver_version_with_a_timestamped_version_when_needed(self):
> ```

So now that you've extracted the version strategy into its own file you can separate this into two tests. 
One will validate that the right strategy is called, the other will stub your class for a mock and check that the specific version returned by it will be used. Right now you're using the 'assert_driver_version' function you wrote just to check for no changes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/shellfoundry/65)*

**Comment by doppleware** [comment]
Reviewed 1 of 4 files at r2, 6 of 6 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/shellfoundry/65)*

**Comment by doppleware** [comment]
Reviewed 4 of 4 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/shellfoundry/65)*

**Comment by doppleware** [comment]
Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/shellfoundry/65)*

**Comment by doppleware** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/test_utilities/test_package_builder.py, line 146 \[r2\]](https://reviewable.io:443/reviews/qualisystems/shellfoundry/65#-KQWvlHDfDbNL6hXGpuB:-KQam5ElnYyWWs4MagoK:b2nhksp) ([raw file](https://github.com/qualisystems/shellfoundry/blob/2c1a17b362bded70465a2e2295b3a70a9e567b5c/tests/test_utilities/test_package_builder.py#L146)):*
<details><summary><i>Previously, doppleware (Roni Dover) wrote…</i></summary>
> So now that you've extracted the version strategy into its own file you can separate this into two tests. 
> One will validate that the right strategy is called, the other will stub your class for a mock and check that the specific version returned by it will be used. Right now you're using the 'assert_driver_version' function you wrote just to check for no changes.
</details>
OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/shellfoundry/65)*

**Comment by kalsky** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/test_utilities/test_package_builder.py, line 146 \[r2\]](https://reviewable.io:443/reviews/qualisystems/shellfoundry/65#-KQWvlHDfDbNL6hXGpuB:-KQamw7AN5irvwaao-Dm:bb7f2mf) ([raw file](https://github.com/qualisystems/shellfoundry/blob/2c1a17b362bded70465a2e2295b3a70a9e567b5c/tests/test_utilities/test_package_builder.py#L146)):*
<details><summary><i>Previously, doppleware (Roni Dover) wrote…</i></summary>
> OK
</details>
done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/shellfoundry/65)*

**Pull request merged**
