### PR TITLE
Dist command was added 

### PR DESCRIPTION
**Pull request by borismod**
## Description
Dist command downloads the driver's dependencies from PyPi to dist/offline_requirements

## Related Stories
connect #70

## Breaking
YES 

## Breaking changes
- ### Breaking change description
      Pack command does not downloads the driver's dependencies anymore. It's available via dist comamnd

---
This change is [Reviewable](https://reviewable.io/reviews/qualisystems/shellfoundry/71)

### CODE REVIEW

**Comment by doppleware** [comment]
Reviewed 24 of 24 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[shellfoundry/bootstrap.py, line 64 \[r1\]](https://reviewable.io:443/reviews/qualisystems/shellfoundry/71#-KQZYm5Mw8v5CAFuzPz1:-KQZYm5Mw8v5CAFuzPz2:bu8lgy5) ([raw file](https://github.com/qualisystems/shellfoundry/blob/8d9d0fdb91109f6bbfb7b80333e002892b8a64fb/shellfoundry/bootstrap.py#L64)):*
> ```Python
> def dist():
>     """
>     Downloads the driver's dependencies from PyPI to dist/offline_requirements
> ```

The description (and functionality should be) - Create a deployable Shell which can be distributed to a production environment.

---

*[shellfoundry/commands/dist_command.py, line 16 \[r1\]](https://reviewable.io:443/reviews/qualisystems/shellfoundry/71#-KQZZkNxyfdoS3QuILm6:-KQZZkNxyfdoS3QuILm7:bj6f91o) ([raw file](https://github.com/qualisystems/shellfoundry/blob/8d9d0fdb91109f6bbfb7b80333e002892b8a64fb/shellfoundry/commands/dist_command.py#L16)):*
> ```Python
>         dest_path = os.path.join(current_path, 'dist', 'offline_requirements')
> 
>         self.dependencies_packager.save_offline_dependencies(requirements_path, dest_path)
> ```

Dist needs to create a shell + package as well as download dependencies

---

*[tests/test_commands/test_dist_command.py, line 11 \[r1\]](https://reviewable.io:443/reviews/qualisystems/shellfoundry/71#-KQZZs0wdJmjx8xUnjKJ:-KQZZs0wdJmjx8xUnjKK:b-q6y6wq) ([raw file](https://github.com/qualisystems/shellfoundry/blob/8d9d0fdb91109f6bbfb7b80333e002892b8a64fb/tests/test_commands/test_dist_command.py#L11)):*
> ```Python
>     def setUp(self):
>         self.setUpPyfakefs()
> ```

Add test_package_created

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/shellfoundry/71)*

**Comment by borismod** [comment]
Review status: 3 of 6 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[shellfoundry/bootstrap.py, line 64 \[r1\]](https://reviewable.io:443/reviews/qualisystems/shellfoundry/71#-KQZYm5Mw8v5CAFuzPz1:-KQZr3Igdau6N92hGLl-:b-896fix) ([raw file](https://github.com/qualisystems/shellfoundry/blob/8d9d0fdb91109f6bbfb7b80333e002892b8a64fb/shellfoundry/bootstrap.py#L64)):*
<details><summary><i>Previously, doppleware (Roni Dover) wrote…</i></summary>
> The description (and functionality should be) - Create a deployable Shell which can be distributed to a production environment.
</details>
Done.

---

*[shellfoundry/commands/dist_command.py, line 16 \[r1\]](https://reviewable.io:443/reviews/qualisystems/shellfoundry/71#-KQZZkNxyfdoS3QuILm6:-KQZr5xLHvLh2czNFoj6:b-896fix) ([raw file](https://github.com/qualisystems/shellfoundry/blob/8d9d0fdb91109f6bbfb7b80333e002892b8a64fb/shellfoundry/commands/dist_command.py#L16)):*
<details><summary><i>Previously, doppleware (Roni Dover) wrote…</i></summary>
> Dist needs to create a shell + package as well as download dependencies
</details>
Done.

---

*[tests/test_commands/test_dist_command.py, line 11 \[r1\]](https://reviewable.io:443/reviews/qualisystems/shellfoundry/71#-KQZZs0wdJmjx8xUnjKJ:-KQZqsDsU-BUkRfiebU1:beepbzb) ([raw file](https://github.com/qualisystems/shellfoundry/blob/8d9d0fdb91109f6bbfb7b80333e002892b8a64fb/tests/test_commands/test_dist_command.py#L11)):*
<details><summary><i>Previously, doppleware (Roni Dover) wrote…</i></summary>
> Add test_package_created
</details>
Pack and dist are called from bootstrapper now, so no test is needed here
 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/shellfoundry/71)*

**Comment by borismod** [comment]
Review status: 3 of 6 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[tests/test_commands/test_dist_command.py, line 11 \[r1\]](https://reviewable.io:443/reviews/qualisystems/shellfoundry/71#-KQZZs0wdJmjx8xUnjKJ:-KQZrMHyCBOdz2qIgXJo:b-896fix) ([raw file](https://github.com/qualisystems/shellfoundry/blob/8d9d0fdb91109f6bbfb7b80333e002892b8a64fb/tests/test_commands/test_dist_command.py#L11)):*
<details><summary><i>Previously, borismod (Boris Modylevsky) wrote…</i></summary>
> Pack and dist are called from bootstrapper now, so no test is needed here
>  
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/shellfoundry/71)*

**Comment by borismod** [comment]
Review status: 3 of 6 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[shellfoundry/bootstrap.py, line 64 \[r1\]](https://reviewable.io:443/reviews/qualisystems/shellfoundry/71#-KQZYm5Mw8v5CAFuzPz1:-KQZrjFFK_QEVyOFKYgD:b-896fix) ([raw file](https://github.com/qualisystems/shellfoundry/blob/8d9d0fdb91109f6bbfb7b80333e002892b8a64fb/shellfoundry/bootstrap.py#L64)):*
<details><summary><i>Previously, borismod (Boris Modylevsky) wrote…</i></summary>
> Done.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/shellfoundry/71)*

**Pull request merged**
